#!/usr/bin/env python3
"""
Read CSV generated by predict_and_prepare_orders and place orders row by row (default dry-run, print payload only).

CSV must contain at least instrument, price, quantity, and price_type.
Auto split by default: quantity >=1000 is split into board lot (x1000) + odd lot remainder.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

import pandas as pd
from masterlink_sdk import (
    MasterlinkSDK,
    Order,
    BSAction,
    PriceType,
    MarketType,
    TimeInForce,
    OrderType,
)


def _env(name: str, default: str | None = None) -> str | None:
    val = os.environ.get(name)
    return val.strip() if val else default


def to_json(obj: Any) -> str:
    def _ser(x: Any):
        if isinstance(x, (str, int, float, bool)) or x is None:
            return x
        if isinstance(x, (list, tuple, set)):
            return [_ser(i) for i in x]
        if isinstance(x, dict):
            return {k: _ser(v) for k, v in x.items()}
        if hasattr(x, "__dict__"):
            return _ser({k: v for k, v in vars(x).items() if not k.startswith("_")})
        return str(x)

    return json.dumps(_ser(obj), ensure_ascii=False, indent=2)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Place orders from CSV (default dry-run)")
    parser.add_argument("csv", type=Path, help="orders CSV (instrument, price, quantity, price_type)")
    parser.add_argument("--user-id", default=_env("MASTERLINK_ID"), help="Login ID (env MASTERLINK_ID)")
    parser.add_argument("--password", default=_env("MASTERLINK_PASSWORD"), help="Trading password (env MASTERLINK_PASSWORD)")
    parser.add_argument("--cert", default=_env("MASTERLINK_CERT"), help="Path to .pfx certificate (env MASTERLINK_CERT)")
    parser.add_argument(
        "--cert-password",
        default=_env("MASTERLINK_CERT_PASSWORD"),
        help="Certificate password (env MASTERLINK_CERT_PASSWORD)",
    )
    parser.add_argument("--account-index", type=int, default=0)
    parser.add_argument("--time-in-force", default="rod", choices=["rod", "ioc", "fok"])
    parser.add_argument("--live", action="store_true", help="Submit real orders; otherwise print payload only")
    return parser.parse_args()


def select_account(sdk: MasterlinkSDK, args: argparse.Namespace):
    missing = [
        name
        for name, value in (
            ("MASTERLINK_ID/--user-id", args.user_id),
            ("MASTERLINK_PASSWORD/--password", args.password),
            ("MASTERLINK_CERT/--cert", args.cert),
            ("MASTERLINK_CERT_PASSWORD/--cert-password", args.cert_password),
        )
        if not value
    ]
    if missing:
        raise SystemExit(f"Missing required login fields:{', '.join(missing)}")

    cert_path = Path(args.cert).expanduser().resolve()
    if not cert_path.exists():
        raise SystemExit(f"Certificate file not found:{cert_path}")

    accounts = sdk.login(args.user_id, args.password, str(cert_path), args.cert_password)
    if not accounts:
        raise SystemExit("Login returned no account")
    if args.account_index < 0 or args.account_index >= len(accounts):
        raise SystemExit(f"account_index {args.account_index} out of range (total {len(accounts)} accounts)")
    return accounts[args.account_index]


def main() -> int:
    args = parse_args()
    df = pd.read_csv(args.csv)
    required = {"instrument", "price", "quantity", "price_type"}
    if not required.issubset(df.columns):
        raise SystemExit(f"CSV missing required columns:{required - set(df.columns)}")

    sdk = MasterlinkSDK()
    account = select_account(sdk, args)
    print("Selected account:")
    print(to_json(account))

    tif_map = {"rod": TimeInForce.ROD, "ioc": TimeInForce.IOC, "fok": TimeInForce.FOK}

    for _, row in df.iterrows():
        code = str(row["instrument"]).strip()
        qty_raw = int(row["quantity"])
        price_val = None if pd.isna(row["price"]) else float(row["price"])
        pt = str(row["price_type"]).lower()
        price_type = PriceType.Market if pt == "market" else PriceType.Limit

        # Auto split: board lot (x1000) + odd lot remainder
        order_specs = []
        lot_qty = (qty_raw // 1000) * 1000
        rem_qty = qty_raw % 1000
        if lot_qty > 0:
            order_specs.append((lot_qty, MarketType.Common))
        if rem_qty > 0:
            order_specs.append((rem_qty, MarketType.Odd))

        for qty, mkt in order_specs:
            if qty <= 0:
                continue
            order = Order(
                buy_sell=BSAction.Buy,
                symbol=code,
                quantity=qty,
                price=None if price_val is None else f"{price_val}",
                market_type=mkt,
                price_type=price_type,
                time_in_force=tif_map[args.time_in_force],
                order_type=OrderType.Stock,
            )
            print("\nOrder payload:")
            print(to_json(order))
            if not args.live:
                continue
            resp = sdk.stock.place_order(account, order)
            print("place_order response:")
            print(to_json(resp))

    if args.live:
        print("\nOrder submission complete. Please confirm status in broker interface.")
    else:
        print("\nDry-run mode: no order submitted.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
